### PR TITLE
[DOCS-143] Describe API Use Case: Create an Asset

### PR DESCRIPTION
**Pull request by mjang-cobalt**
I've set up our first API Use Case Doc in this PR. To see how this build would look in our documentation, see:

- https://deploy-preview-146--cobalt-docs.netlify.app/apiusecases/
- https://deploy-preview-146--cobalt-docs.netlify.app/apiusecases/create_asset/

We've brainstormed some use cases in a Google doc attached to the (private) Jira.

I've included some variables to ensure that we have "common" names for values like `api-token`. 

- In the MD files, I call the variable with values like `{{% api-token %}}`
   - That variable calls values from the layouts/shortcodes subdirectory of this repo.

Note: the final REST call to include an asset attachment isn't working atm due to an _internal_ bug.

### CODE REVIEW

**Comment by atolac** [comment]
question from 1st time API user: are certain roles needed to access the API or is it available all org members ?

**Comment by micobal** [comment]
I think it will help to clarify in the docs if  the public API available to all org members, or does it work only for certain roles ?

**Comment by mjang-cobalt** [comment]
> I think it will help to clarify in the docs if the public API available to all org members, or does it work only for certain roles ?

Thanks, I need to test the various scenarios.

- I've confirmed that it works for an _admin_ and a _member_ IF that user is a member of an org
- I should also test the `pentest-collaborator` (and `lead`)

**Comment by micobal** [comment]
Thanks for checking, just in case others are wondering the same thing, maybe it's worth quickly mentioning in the docs that API is available for all user roles ?

**Comment by mjang-cobalt** [comment]
Hi @atolac

Yes, it should be available to all org members (I just double-checked)

I don't see your note in the PR. If I accidentally deleted it, I apologize.

**Comment by mjang-cobalt** [comment]
> Thanks for checking, just in case others are wondering the same thing, maybe it's worth quickly mentioning in the docs that API is available for all user roles ?

See [these lines](https://github.com/cobalthq/cobalt-product-public-docs/pull/146/files#diff-bb5880766296b4af07d17eeac618d95c263ee51255add9d3e4e1cd0cbcc89404R14-R19) for my update

**Comment by mjang-cobalt** [comment]
Merging, based in part on PM review.

**Pull request merged**
