### PR TITLE
[FX-4406] Update hugo and docsy

### PR DESCRIPTION
**Pull request by TaylorBriggs**
## Changelog

This updates both hugo and the docsy theme. Overall the site appears the same, but there are some notable styling differences in the latest version of docsy. However, some of the bugs that were present before have been fixed.

| Description | Screenshot |
| ----------- | ---------- |
| Page Info &mdash; Before | Screenshot 2024-10-02 at 3 57 08 PM |
| Page Info &mdash; After  | Screenshot 2024-10-02 at 3 57 33 PM |
| Sidebar Nav &mdash; Before | Screenshot 2024-10-02 at 3 59 28 PM |
| Sidebar Nav &mdash; After  | Screenshot 2024-10-02 at 3 59 51 PM |

## Preview This Change

To see how this change looks in production, scroll down to **Deploy Preview**. Select the link that looks like `https://deploy-preview-<num>--cobalt-docs.netlify.app/`

## Variables

Help us support a “Write once, publish everywhere” single source of truth. If you see a line that looks like:

`{{% asset-categories %}}`

You’ve found a [shortcode](https://gohugo.io/content-management/shortcodes/) that we include in multiple documents.

You’ll find the content of the shortcode in the following directory:

https://github.com/cobalthq/cobalt-product-public-docs/tree/main/layouts/shortcodes

That shortcode has the same base name as what you see in the PR, such as `asset-categories.html`.

## Checklist for PR Author

[ ] Did you check for broken links and alt text?

Be sure to check for broken links and Alt Text issues. We have a partially automated process,
as described in this section of our repository README:
[Test Links and Alt Attributes](https://github.com/cobalthq/cobalt-product-public-docs/blob/main/README.md#test-links-and-alt-attributes).

### CODE REVIEW

**Comment by kittaakos** [comment]
I like that the sidebar shows if there are subpages 💪 

Before:
Screenshot 2024-10-07 at 19 52 54

After:
Screenshot 2024-10-07 at 19 53 00


----
Maybe it's unrelated to this change, but the last change time for the dev preview is bogus.

Screenshot 2024-10-07 at 19 54 20

**Comment by TaylorBriggs** [comment]
> Maybe it's unrelated to this change, but the last change time for the dev preview is bogus.

Yeah, I don't know what's going on with this. It should be getting that from [git](https://gohugo.io/methods/page/gitinfo/#last-modified-date), but maybe I screwed something up with the configuration and/or how I'm accessing the page variable.

**Review by eugenerevzin — APPROVED** [review]
Looks great!

**Comment by TaylorBriggs** [comment]
The "Last modified" date should be fixed now.

**Review by mtsuji-cobalt — COMMENTED** [review]
• could we add some spacing between the buttons? maybe approximately 8px:
Footer

• i also noticed that we don't show the specific section links anymore, like this:
SectionLinks

i think this doesn't affect current links that do direct to specific sections in the docs. but if we do want to continue linking to specific sections, i wouldn't be sure of the exact URL to use / how to generate it.

• also just pointing out another difference: this new version has an option for anyone to 'View page source.' was that available before and we chose not to show it or is it a new option with this version?

• not a big deal but randomly noticed that some pages have this blue divider line at the bottom while others don't:
DividerLine

**Review by mtsuji-cobalt — COMMENTED** [review]
**i just noticed 3 things that seem off relating to API docs:**

**1.** there is a random space below the 'API documentation' option in the main ProDocs nav:

ProDocsNav_Space
_*Edit: the space is actually clickable and takes me to /cobalt-api/v1_

**2.** the API doc nav is overlapping with the ProDoc's nav, and i can't click on any of its options:

APIDocsNav


**3.** the scroll action is also a bit strange - it highlights the section only very briefly when you reach it:


https://github.com/user-attachments/assets/41151d3f-43b8-45a9-b111-668f8e22b03e

**Comment by TaylorBriggs** [comment]
@mtsuji-cobalt thanks! I just fixed up the navigation links and styling for the API docs.

**Comment by mtsuji-cobalt** [comment]
> @mtsuji-cobalt thanks! I just fixed up the navigation links and styling for the API docs.

thanks @TaylorBriggs. all looks good now but there's something weird going on with the nav highlighting action for the API docs. i think it's somehow connected to the Findings section. everything up to the Findings section scrolls through fine but then from there on, the entire Findings to Webhooks options sometimes expand and are highlighted in black:
Screenshot 2024-10-09 at 13 58 40

https://github.com/user-attachments/assets/644ed073-b50c-481c-a0dd-b13b8d6b0e58

**Comment by TaylorBriggs** [comment]
@mtsuji-cobalt those pages are using iframes to include the content from another site. I think this is already acting this way on our [current page](https://docs.cobalt.io/cobalt-api/v2/).

We probably need to figure out why it's doing that from [this other hugo site](https://github.com/cobalthq/cobalt-api-docs) and fix the problem there.

**Review by mtsuji-cobalt — APPROVED** [review]

**Pull request merged**
