### PR TITLE
Display changes and feedback removal

### PR DESCRIPTION
**Pull request by stef-cobaltio**
Removed theme files (feedback.html) to eliminate the feedback section from the footer of parent pages; the original file is archived on Google Drive for future implementation.

Furthermore, adjusted the page layout to prevent the display of child pages beneath the parent page content.

Added: 
no_list

no_list: true to the page headers for index.md (parent) pages, so that they don't publish child pages below the page content. See before and after attached. 
before
after

## Preview This Change

To see how this change looks in production, scroll down to **Deploy Preview**. Select the link that looks like `https://deploy-preview-<num>--cobalt-docs.netlify.app/`

## Variables

Help us support a “Write once, publish everywhere” single source of truth. If you see a line that looks like:

`{{% asset-categories %}}`

You’ve found a [shortcode](https://gohugo.io/content-management/shortcodes/) that we include in multiple documents.

You’ll find the content of the shortcode in the following directory:

https://github.com/cobalthq/cobalt-product-public-docs/tree/main/layouts/shortcodes

That shortcode has the same base name as what you see in the PR, such as `asset-categories.html`.

## Checklist for PR Author

[ ] Did you check for broken links and alt text?

Be sure to check for broken links and Alt Text issues. We have a partially automated process,
as described in this section of our repository README:
[Test Links and Alt Attributes](https://github.com/cobalthq/cobalt-product-public-docs/blob/main/README.md#test-links-and-alt-attributes).

### CODE REVIEW

**Comment by mtsuji-cobalt** [comment]
Could you clarify what was changed with 

> Furthermore, adjusted the page layout to prevent the display of child pages beneath the parent page content.

A before and after screenshot could help also

**Comment by stef-cobaltio** [comment]
Updated the PR description with images to illustrate what was changed to remove the child pages from duplicating to display within the parent page at the footer of the page content.

**Comment by mtsuji-cobalt** [comment]
> Updated the PR description with images to illustrate what was changed to remove the child pages from duplicating to display within the parent page at the footer of the page content.

ok, i get it now. it makes sense to remove these bc i realized that the page subheaders (which i think we should remove from all pages) are shown as the footer page content subheaders as well:
Screenshot 2024-11-13 at 04 52 11

but i am seeing these footer content across parent pages still. there are other index.md files outside the first-level nav options:
Screenshot 2024-11-13 at 04 51 18

**Comment by stef-cobaltio** [comment]
Thanks @mtsuji-cobalt for catching this, I just went in and adjusted all of the other index.md pages that had child pages under them.

Agree about the description - I need to check on one thing before we remove them though.

**Review by mtsuji-cobalt — APPROVED** [review]

**Pull request merged**
